name: marp-GitHub-actions
on: [push]
jobs:
  marp-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update & sudo apt-get install jq
      - name: grant permissions to shell script
        run: chmod -R 777 ./static/
      - run: |
          input_dir=$(cat config.json | jq -r .input_dir)
          output_dir=$(cat config.json | jq -r .output_dir)
          output_format=$(cat config.json | jq -r .output_format)
          echo "::set-output name=DIR::${output_dir}"
          echo "::set-output name=FORMAT::${output_format}"
        id: config
      - run: for f in ./markdown/*; do a=${f##*/};docker run --rm -u root --init -v "$(pwd):/home/marp/app/" -e LANG=$LANG marpteam/marp-cli markdown/${a%.*}.md --html -o static/${a%.*}.html;done
      - uses: actions/upload-artifact@v2
        with:
          name: output_slide
          path: ${{steps.config.outputs.DIR}}.${{steps.config.outputs.FORMAT}}
